"""empty message

Revision ID: 270d3e116b9f
Revises: 6957092bb108
Create Date: 2024-09-27 16:58:56.357588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '270d3e116b9f'
down_revision = '6957092bb108'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('diameter', sa.String(), nullable=False),
    sa.Column('rotation_period', sa.String(), nullable=False),
    sa.Column('orbital_period', sa.String(), nullable=False),
    sa.Column('gravity', sa.String(), nullable=False),
    sa.Column('population', sa.String(), nullable=False),
    sa.Column('climate', sa.String(), nullable=False),
    sa.Column('terrain', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planets')
    # ### end Alembic commands ###
